# Conclusion

In conclusion, as we take an overview of the traffic data in the New York State, we find that the general trend and level are very similar between 2018 and 2019, where the streets are busy in the first three months in each year. However, the data in the first half of 2020 seems quite abnormal, which suggests a possibility that it is affected by COVID-19. Therefore, we compare the traffic data and the COVID-19 data in each month, and conclude that people will be more likely to stay home and do not drive their cars when there is an outbreak of the pandemic.

We then use a parallel coordinate plot to see the relationships between different variables, and draw the conclusion that New York City, with a 0 volume in rural area, is quite different from other regions. As we move on to study the distribution of vehicle count among different regions, we find that streets in New York City are always the busiest among regions in New York State from 2018 to 2020. Moreover, we use bar charts to find which streets are the busiest in New York State, and the result suggests that the busiest streets are mostly from New York City (NYC) and Hauppauge in 2018 and 2019 but it turns out that the top 15 busiest streets are all from NYC in 2020.

We then conduct research on the difference of traffic volume among different day of week. We first use a boxplot to show the distribution of vehicle count among different day of week, and it turns out that streets in New York States are busiest on Monday, Tuesday, and Wednesday, and least busy on Friday from 2018 to 2020. Then, we compare the difference of traffic volume on weekdays and weekends among different regions using a diverging stacked bar chart, and concludes that regions like Hauppauge and New York City have much more cars on weekdays than weekends, which somehow correlated with the location of busiest streets we found previously.

Moreover, as we move forward to see the exact hours that have the heaviest traffic using heat map , we find that the counts are concentrated from 16:00 to 18:00 and from 8 am to 9 am on weekdays, which are exactly the hours when people go to work and return home. Also, the number of hours with relatively heavier traffic decreased a lot in 2020, probably due to the pandemic when more people started to work remotely.

We then focus on the difference in vehicle counts among different lanes of streets. With a mosaic plot, we discover that there tends to be more cars in the middle lanes of a street, and fewer cars in the side lanes of a street and there tends to be more cars in streets with many lanes than in streets with few lanes, which suggests big streets are more likely to be busy streets.

Finally, we make an interactive graph to help users better know the trend of the vehicle count in New York State in recent years and know discover the vehicle count changed among different regions.